FROM gmauro/ansible:2.1-ubuntu

WORKDIR /tmp

ADD docker.yml /tmp/local.yml
ADD vars /tmp/roles/ansible-obb-server/vars
ADD tasks /tmp/roles/ansible-obb-server/tasks
ADD templates /tmp/roles/ansible-obb-server/templates

RUN git clone https://github.com/gmauro/ansible-java /tmp/roles/ansible-java \
 && git clone https://github.com/gmauro/ansible-ice /tmp/roles/ansible-ice \
 && ansible-playbook -i localhost, local.yml -e "@roles/ansible-obb-server/vars/main.yml"
