- name: create omero group
  group: name={{ OMEROGROUP }} state=present

- name: create omero user
  user: name={{ OMEROUSER }} password={{ PASSWORD }} update_password=always shell=/bin/bash home=/home/{{ OMEROUSER }} group={{ OMEROGROUP }}
