- include: install_packages.yml
  when: install_packages

- include: add_user.yml
  when: add_user

- include: install_obb.yml
  become: yes
  become_method: su
  become_user: "{{ OMEROUSER }}"
  when: install_obb

- include: config_supervisor.yml
  when: config_supervisor

